purge_purger_http.settings.*:
  type: config_entity
  label: 'HTTP Purger'
  mapping:
    id:
      type: string
      label: 'ID'
      translatable: false
    invalidationtype:
      type: string
      label: 'Invalidation Type'
      translatable: false
    hostname:
      type: string
      label: 'The hostname to connect to for the custom outbound HTTP request.'
      translatable: false
    port:
      type: integer
      label: 'The port to connect to for the custom outbound HTTP request.'
      translatable: false
    path:
      type: string
      label: 'The path to trigger a cache invalidation for.'
      translatable: false
    request_method:
      type: string
      label: 'The HTTP request method to use for the HTTP Purger.'
      translatable: false
    timeout:
      type: float
      label: 'Float describing the timeout of the request in seconds. Use 0 to wait indefinitely (the default behavior).'
      translatable: false
    connect_timeout:
      type: float
      label: 'Float describing the number of seconds to wait while trying to connect to a server. Use 0 to wait indefinitely (the default behavior).'
      translatable: false
    max_requests:
      type: integer
      label: 'Maximum number of HTTP requests that can be made during the runtime of one request (including CLI). The higher this number is set, the more - CLI based - scripts can process but this can also badly influence your end-user performance when using runtime-based queue processors.'
      translatable: false
